### ISSUE TITLE
API and YAML

### ISSUE THREAD

**Issue by zeusstl** [Picovoice/cheetah#116]
Hello,

I've liked what we've seen so far with Cheetah.

(I'm interested in potentially using the paid service, but have not heard back from support after sending 2 messages on the contact page over a week.)

1. How can we add a long list of vocabulary?
2. Is there an API that we can use for updating the list?

Is there a better way to contact you or support?

Thanks!

**Comment by zeusstl** [comment]
Of course, as soon as I wrote to you, we finally figured out the format for the adding vocabulary with YAML by adding some and downloading the YAML. (It might make sense to add a format in the documentation or maybe as a placeholder in the YAML input field.)

Is there a limit to how many vocabulary and boost we can add?

I added a list of words and now I am unable to view the model. I get this message:
"Sorry, we could not fetch this model"

FYI... There seems to be a small bug. When adding yaml, it does not update the model. The workaround we used was to add the yaml and then add one more vocabulary manually. This brought up the "Save" button and we were able to save the model.

1. Curious about adding a long list of vocabulary.
2. Still interested in adding the yaml via an api to update the model a bit more dynamically.

Please let me know if there are possible.

Thanks!

**Comment by laves** [comment]
@zeusstl - thank you for your report, we will look into the issues you've encountered and report back.

Thank you for posting the issue here - GitHub is the correct channel for technical support. Our website contact form is for sales or partnership inquiries and is not managed by the engineering team.

As for your questions: 

1) As you have found, long lists of vocabulary can be added through the Import YAML feature. In theory, there is no limit to the number of words you can add to Cheetah, but in practice, there are some limitations with the size of YAML you can upload in our Picovoice Console. You should be comfortably able to add many thousands of words through Console. If you encounter a limit, please contact sales and tell us more about your project and we may be able to support you to surpass the limitation.

2) There is currently no API available for updating the wordlist and delivering models on the fly. Custom solutions are always available for large projects and for that, I would also direct you to sales to inform us more about your project

**Comment by zeusstl** [comment]
@laves Thanks for the quick answer. That's unfortunate about no API, but if we move forward with it we would probably need an api for updating the model.

(I've reached out to support twice and mentioned that we're potentially interested in a paid plan and never heard back for quite a few days now. Just letting you know in case the form is broken or going to spam or something.)
