### ISSUE TITLE
Detecting "uhhs" and "ahhs"?

### ISSUE THREAD

**Issue by ridoy** [Picovoice/cheetah#153]
I'd like to be able to detect "uhhs" and "ahhs" with Cheetah. Is that possible currently?

**Comment by kenarsa** [comment]
I don't think cheetah is optimized to find these sounds but we have not benchmarked it for this usecase.

**Comment by dotansh** [comment]
Having a similar problem...
I am trying to add words to the Custom Vocabulary and Boost Words lists, but this has no effect on the results...
What I am doing is:
1. update the lists
2. Download the Model file.
3. Execute:
npx pvbase64 -i [Model file name] -o model.js
4. add model.js to the demo instead of cheetah_params.js
5. Test the demo

Look like all the above has very small edffect on the resluts (if any).
What am I doing wrong?
